# Generated by Django 4.2.2 on 2023-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_story_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('content', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('cover_photo', models.ImageField(blank=True, upload_to='static/poem_covers')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static/author_profiles/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='bio',
            field=models.TextField(),
        ),
    ]
