# Generated by Django 4.2.2 on 2023-06-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_poem_alter_author_profile_image_alter_story_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.author'),
        ),
    ]
