# Generated by Django 4.2.2 on 2023-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_poem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('bio', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('cover_photo', models.ImageField(blank=True, upload_to='./static/story_covers')),
            ],
        ),
    ]
