# Generated by Django 4.2.2 on 2023-06-30 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_remove_story_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
