# Generated by Django 4.2.2 on 2023-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_alter_poem_content_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(),
        ),
    ]
