# Generated by Django 4.2.2 on 2023-06-30 11:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_alter_poem_content_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
