# Generated by Django 4.2.2 on 2023-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_alter_poem_bio_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='first_letter',
            field=models.TextField(blank=True, max_length=1),
        ),
    ]
