# Generated by Django 4.2.2 on 2023-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_story_first_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/author_profiles/'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='images/poem_covers'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='images/story_covers'),
        ),
    ]
