# Generated by Django 4.2.2 on 2023-07-01 02:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_alter_story_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
