# Generated by Django 4.2.2 on 2023-09-12 09:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0026_alter_poem_bio_alter_poem_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_letter', models.TextField(blank=True, max_length=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('desk_image', models.ImageField(blank=True, upload_to='images/desk_covers/')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.author')),
            ],
        ),
    ]
