# Generated by Django 4.2.2 on 2023-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
