# Generated by Django 4.2.2 on 2023-09-12 10:48

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0028_sports_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='desk_image',
            field=models.ImageField(blank=True, upload_to=stories.models.story_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=stories.models.sports_cover_upload_path),
        ),
    ]
