# Generated by Django 4.2.2 on 2023-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0031_rename_sports_sport_alter_poem_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
