# Generated by Django 4.2.2 on 2023-09-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0032_alter_sport_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='publication_date',
        ),
    ]
