# Generated by Django 4.2.2 on 2023-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0033_remove_sport_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
